backend:
  name: git-gateway
  branch: master

media_folder: "src/assets/images/uploads" # Folder where user uploaded files should go
public_folder: "assets/images/uploads"
publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "blog" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Blog" # Used in the UI, ie.: "New Post"
    folder: "blog" # (src/assets/blog) The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string", required: false }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: false,
        }
      - {
          label: "Publish",
          name: "publish",
          widget: "boolean",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "careers"
    label: "Job"
    folder: "jobs"
    create: true
    slug: "{{position}}-{{location}}"
    fields:
      - {
          label: "Location",
          name: "location",
          widget: "string",
          required: true,
        }
      - {
          label: "Overview",
          name: "overview",
          widget: "string",
          required: true,
        }
      - {
          label: "Job Title",
          name: "position",
          widget: "string",
          required: true,
        }
      - {
          label: "Requirements",
          name: "requirements",
          widget: "string",
          required: true,
        }
      - {
          label: "Job Description",
          name: "body",
          widget: "markdown",
          required: true,
        }
      - {
          label: "Responsibilities",
          name: "responsibilities",
          widget: "string",
          required: true,
        }
      - { label: "Status", name: "status", widget: "string", required: true }
